### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by papodaca** [pivotal/angular-directive-d3-treemap#1]
Want to be able to use this in a project. Need clear licensing.

**Comment by tomwhoiscontrary** [comment]
@bengro We did this on the beach, right? If so, it's our choice of license. Unless you object, i'll add a BSD license declaration tomorrow. @papodaca prod me if i don't.

**Comment by textbook** [comment]
It says MIT in the `package.json`

**Comment by bengro** [comment]
@tomwhoiscontrary Yes, that was created on the beach. Feel free to change it to whatever you think is most adequate.

**Comment by papodaca** [comment]
Sorry I brought all this nonsense up. Per our policy there needs the be either a license or copying file in the root of the repo or a mention of the license in the readme.

**Comment by bengro** [comment]
No, not at all!

I changed the license to BSD and added a LICENSE-BSD file, see b92d0de374436b9a4fbc0649933f3f849df41500.

@tomwhoiscontrary please check everything is to your liking... e.g. I'm not sure the copyright holder 'Pivotal' is a legal person.

**Comment by tomwhoiscontrary** [comment]
Looks good to me!

**Comment by tomwhoiscontrary** [comment]
Silence implies satisfaction; closing.
